name: Deploy to Yandex Cloud Functions

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Deploy Function
      id: sls-func
      uses: yc-actions/yc-sls-function@v2
      with:
        yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
        folder-id: ${{ secrets.FOLDER_ID }}
        function-name: 'partybook-on-func'
        runtime: 'python312'
        memory: '256Mb'
        entrypoint: 'index.handler'
        service-account-id: ${{ secrets.SERVICE_ACCOUNT_ID }}
        environment: |
          PRODUCTION_TOKEN=${{ secrets.PRODUCTION_TOKEN }}
          TEST_TOKEN=${{ secrets.TEST_TOKEN }}
          YDB_DATABASE=${{ secrets.YDB_DATABASE }}
          YDB_ENDPOINT=${{ vars.YDB_ENDPOINT }}
        include: |
          **/*.py
          **/*.json
          **/*.txt
        exclude: |
          **/*.ts
          .github/**
          tests/**
          venv/**
          **/*.ts
          .gitignore
          LICENSE
