name: Deploy Auto Sender Function to Yandex Cloud

on:
  push:
    branches: [ master ]
    paths:
      - 'app/auto_sender.py'
      - '.github/workflows/yacloud-func-python AUTO_SENDER.yml'
  workflow_dispatch:

env:
  YC_FOLDER_ID: ${{ secrets.YC_FOLDER_ID }}
  YC_OAUTH_TOKEN: ${{ secrets.YC_OAUTH_TOKEN }}

jobs:
  deploy-auto-sender:
    runs-on: ubuntu-latest
    name: Deploy Auto Sender Function
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        pip install -r app/requirements.txt
        
    - name: Configure Yandex Cloud CLI
      uses: yc-actions/yc-cli@v2
      with:
        yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
        
    - name: Deploy Auto Sender Function
      id: sls-auto-sender
      uses: yc-actions/yc-sls-function@v2
      with:
        # Function configuration
        function-name: 'auto-sender-function'
        function-description: 'Автоматическая отправка чанков пользователям по расписанию'
        runtime: 'python39'
        entrypoint: 'auto_sender.handler'
        memory: '512Mb'
        timeout: '60s'
        environment: 'TESTING'
        
        # Source code
        source-path: 'app/'
        
        # Environment variables
        env-vars: |
          YDB_ENDPOINT=${{ secrets.YDB_ENDPOINT }}
          YDB_DATABASE=${{ secrets.YDB_DATABASE }}
          TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}
          
        # Service account
        service-account-id: ${{ secrets.YC_SERVICE_ACCOUNT_ID }}
        
    - name: Create Timer Trigger for Auto Sender
      id: timer-trigger
      run: |
        # Создаем триггер по расписанию (каждый час)
        yc serverless trigger create timer \
          --name auto-sender-timer \
          --cron-expression "0 * * * *" \
          --invoke-function-name auto-sender-function \
          --invoke-function-tag \$latest \
          --invoke-function-service-account-id ${{ secrets.YC_SERVICE_ACCOUNT_ID }}
          
    - name: Deploy Summary
      run: |
        echo "✅ Auto Sender Function deployed successfully!"
        echo "📅 Timer trigger created: runs every hour"
        echo "🔧 Function name: auto-sender-function"
        echo "⏰ Timeout: 60 seconds"
        echo "💾 Memory: 512 MB"
